/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as E05IndexRouteRouteImport } from './routes/e05/index.route'
import { Route as E04IndexRouteRouteImport } from './routes/e04/index.route'
import { Route as E03IndexRouteRouteImport } from './routes/e03/index.route'
import { Route as E02IndexRouteRouteImport } from './routes/e02/index.route'
import { Route as E01IndexRouteRouteImport } from './routes/e01/index.route'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const E05IndexRouteRoute = E05IndexRouteRouteImport.update({
  id: '/e05/',
  path: '/e05',
  getParentRoute: () => rootRouteImport,
} as any)
const E04IndexRouteRoute = E04IndexRouteRouteImport.update({
  id: '/e04/',
  path: '/e04',
  getParentRoute: () => rootRouteImport,
} as any)
const E03IndexRouteRoute = E03IndexRouteRouteImport.update({
  id: '/e03/',
  path: '/e03',
  getParentRoute: () => rootRouteImport,
} as any)
const E02IndexRouteRoute = E02IndexRouteRouteImport.update({
  id: '/e02/',
  path: '/e02',
  getParentRoute: () => rootRouteImport,
} as any)
const E01IndexRouteRoute = E01IndexRouteRouteImport.update({
  id: '/e01/',
  path: '/e01',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/e01': typeof E01IndexRouteRoute
  '/e02': typeof E02IndexRouteRoute
  '/e03': typeof E03IndexRouteRoute
  '/e04': typeof E04IndexRouteRoute
  '/e05': typeof E05IndexRouteRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/e01': typeof E01IndexRouteRoute
  '/e02': typeof E02IndexRouteRoute
  '/e03': typeof E03IndexRouteRoute
  '/e04': typeof E04IndexRouteRoute
  '/e05': typeof E05IndexRouteRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/e01/': typeof E01IndexRouteRoute
  '/e02/': typeof E02IndexRouteRoute
  '/e03/': typeof E03IndexRouteRoute
  '/e04/': typeof E04IndexRouteRoute
  '/e05/': typeof E05IndexRouteRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/e01' | '/e02' | '/e03' | '/e04' | '/e05'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/e01' | '/e02' | '/e03' | '/e04' | '/e05'
  id: '__root__' | '/' | '/e01/' | '/e02/' | '/e03/' | '/e04/' | '/e05/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  E01IndexRouteRoute: typeof E01IndexRouteRoute
  E02IndexRouteRoute: typeof E02IndexRouteRoute
  E03IndexRouteRoute: typeof E03IndexRouteRoute
  E04IndexRouteRoute: typeof E04IndexRouteRoute
  E05IndexRouteRoute: typeof E05IndexRouteRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/e05/': {
      id: '/e05/'
      path: '/e05'
      fullPath: '/e05'
      preLoaderRoute: typeof E05IndexRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/e04/': {
      id: '/e04/'
      path: '/e04'
      fullPath: '/e04'
      preLoaderRoute: typeof E04IndexRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/e03/': {
      id: '/e03/'
      path: '/e03'
      fullPath: '/e03'
      preLoaderRoute: typeof E03IndexRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/e02/': {
      id: '/e02/'
      path: '/e02'
      fullPath: '/e02'
      preLoaderRoute: typeof E02IndexRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/e01/': {
      id: '/e01/'
      path: '/e01'
      fullPath: '/e01'
      preLoaderRoute: typeof E01IndexRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  E01IndexRouteRoute: E01IndexRouteRoute,
  E02IndexRouteRoute: E02IndexRouteRoute,
  E03IndexRouteRoute: E03IndexRouteRoute,
  E04IndexRouteRoute: E04IndexRouteRoute,
  E05IndexRouteRoute: E05IndexRouteRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
